version: '3.8'
services:
  mova-api:
    build: .
    command: npm run dev
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - APP_PORT=9000
      - ENV_ID=dev
      - NODE_ENV=development
    #network_mode: bridge
    volumes:
      - .:/app/
    depends_on:
      - mova-db
  mova-db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 9002:3306
    environment:
      MYSQL_USER: mova
      MYSQL_PASSWORD: secret-to-mova-db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mova
    restart: always
    #network_mode: bridge
    volumes:
      - mova-db:/var/lib/mysql
volumes:
  mova-db:
